"""
SQLAlchemy model for orders.

Represents a customer order in the system. Each order belongs to a customer
(`client_id`) and contains aggregated totals for the items purchased. In a
full implementation there would also be an ``OrderItem`` model referencing
products, but this simplified version focuses on the order header only.
"""

from __future__ import annotations

import uuid
from sqlalchemy import (
    Column,
    BigInteger,
    Boolean,
    DateTime,
    Integer,
    String,
    SmallInteger,
    CHAR,
    func,
    CheckConstraint,
)
from sqlalchemy.dialects.postgresql import UUID

from app.db.base import Base


class Order(Base):
    """Order header information for a purchase."""

    __tablename__ = "orders"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # An auto-incrementing order number can be generated by the database.
    order_number = Column(Integer, autoincrement=True, unique=True, index=True)
    client_id = Column(UUID(as_uuid=True), nullable=False)
    subtotal_cents = Column(BigInteger, nullable=False)
    discount_cents = Column(BigInteger, nullable=False, default=0)
    shipping_cents = Column(BigInteger, nullable=False, default=0)
    tax_cents = Column(BigInteger, nullable=False, default=0)
    total_cents = Column(BigInteger, nullable=False)
    currency = Column(CHAR(3), nullable=False, server_default="USD")
    status = Column(String, nullable=False, server_default="pending")
    notes = Column(String, nullable=True)
    internal_notes = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    confirmed_at = Column(DateTime(timezone=True), nullable=True)
    shipped_at = Column(DateTime(timezone=True), nullable=True)
    delivered_at = Column(DateTime(timezone=True), nullable=True)
    cancelled_at = Column(DateTime(timezone=True), nullable=True)
    version = Column(Integer, nullable=False, server_default="1")

    __table_args__ = (
        CheckConstraint("subtotal_cents >= 0", name="ck_order_subtotal_non_negative"),
        CheckConstraint("discount_cents >= 0", name="ck_order_discount_non_negative"),
        CheckConstraint("shipping_cents >= 0", name="ck_order_shipping_non_negative"),
        CheckConstraint("tax_cents >= 0", name="ck_order_tax_non_negative"),
        CheckConstraint("total_cents >= 0", name="ck_order_total_non_negative"),
    )
